services:
  db:
    image: postgres:latest
    container_name: findirai_db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: findirai
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "3001:3000"
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client/config-overrides.js:/usr/src/app/config-overrides.js

volumes:
  db_data: